### ISSUE TITLE
zvelo.io is down

### ISSUE THREAD

**Issue by JulienTant** [zvelo/ttlru#10]
Hi,

I'm sending you that issue because the website is down, preventing our team to use the package in our project. We have an HTTP 525 (SSL handshake failed)

**Comment by JulienTant** [comment]
Looks like it's back from the dead. I'm closing this!

**Comment by drekar** [comment]
Thanks @JulienTant, we transitioned to an auto-renewing SSL certificate system, resulting in some downtime during the transition.
