### ISSUE TITLE
Usage of github.com/smartystreets/goconvey brings in unnecessary dependencies

### ISSUE THREAD

**Issue by jbub** [zvelo/ttlru#7]
Hello, first, thanks for this lovely project, it works very well for me!

Now given that the project uses convey for testing it brings heavy dependecies like:

```
zvelo.io/ttlru
zvelo.io/ttlru.test
github.com/smartystreets/goconvey/convey
github.com/jtolds/gls
github.com/gopherjs/gopherjs/js
```

Would you maybe accept a PR that uses standard library testing framework or some other less heavy testing framework, maybe just the popular `github.com/stretchr/testify/assert` for assertions :) Thank you!

**Comment by joshuarubin** [comment]
Yeah, that sounds like a good idea. I no longer have access to this repo though. Maybe @zvbuhl or @drekar could help.

**Comment by drekar** [comment]
Agreed on this update suggestion.  Going to add it to our short-list.  Thanks @jbub

**Comment by jbub** [comment]
Here is the PR https://github.com/zvelo/ttlru/pull/8
